AWSTemplateFormatVersion: 2010-09-09
Description: >-
  auth-portal
Transform:
- AWS::Serverless-2016-10-31
Resources:
  SignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/signup.signupHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A signup API
      Events:
        Api:
          Type: Api
          Properties:
            Path: /signup
            Method: POST

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
